database:
  hostname: 127.0.0.1
  username: root
  password: 111111
  database: raymond

system:
  user_default_acl: false
  language:
    en: English
    zh-hk: 中文

user:
  company: HostLink
  2-step verification: 0
  2-step verification white list: null
  footer_content:
  copyright-year: 2020
  copyright-url: https://www.hostlink.com.hk
  copyright-name: HostLink
  logo:

  search-form: false
  default-skin: skin-blue

  domain:

  smtp:
  smtp-username:
  smtp-password:
  smtp-port:
  smtp-auto-tls: 1

  return-path:

  password-length: 6

  log-save: true

  development: true

  auth-lockout: true

hostlink-fileman:
  key: test1234
  basepath: /uploads

jwt:
  key: 1QekHjUGABWFYpoEYVJb1cgmqx80u3JotKGi6Qa157Gmm8Tf6hsmosd9PRvrRL8dRJbZrIbmfrSo4aC0ew1iDqO1hvIOEd8KCslfE4OFePR593D9FaCYmhHXjbKrPD2Z0rOiAN7V6E4GmrPX4clB6yRyrmRlHNpcyr1suoH60ftnFNpZUgLnnk194tF3Q3jg3JA25C5n7sMlrtpVUCfECIGQrAhlOPNQQfi034VmQFQdAYqJiBPAXBSnvlFp8Hn9
