directive @hasRole on FIELD_DEFINITION
scalar JSON

type Query{
    me:String
}

type Subscription{
    createUser(username:String!,password:String!,first_name:String!,last_name:String,
    phone:String,email:String!,addr1:String,addr2:String,addr3:String,
    join_date:String,status:Int!,expiry_date:String,usergroup_id:[Int],
    language:String,default_page:String):Int
}

type Mutation{
    updateUser(user_id:Int!,data:UserInput):Boolean
   
}

input UserInput{
    first_name:String
    last_name:String
    
}
