directive @hasRole on FIELD_DEFINITION
scalar JSON

type Mutation{
    me:Me
    login(username:String!,password:String!,code:String):Me
    UserGroup(usergroup_id:Int!):UserGroup
    forgotPassword(username:String!,email:String!):Boolean
    updateMyInfo(first_name:String!,last_name:String,phone:String,email:String!):Me @hasRole(role:[Administrators,Users])
    resetPassword(new_password:String!):Boolean @hasRole(role:[Administrators,Users])
    updateFavoriteSequence(id:[Int!]!):Boolean @hasRole(role:[Administrators,Users])
    addFavorite(label:String!,link:String):Boolean @hasRole(role:[Administrators,Users])
}

type Query{
    me:Me
    credentialRequestOptions(username:String!):String
    loginWebAuthn(username:String!,assertion:String!):Boolean
    UserGroup(usergroup_id:Int!):UserGroup
    UserGroups:[UserGroup]
    
}

type Me{
    user_id:Int
    username:String
    first_name:String
    last_name:String
    group:[UserGroup]
    credentialCreationOptions:String
    registrationWebAuthn(attestion:String!):Boolean
    jwt:String
}

type UserGroup{
    name:String
    addUser(user_id:Int!):Boolean
    removeUser(user_id:Int!):Boolean
}

